# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nuechter/slam6d/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nuechter/slam6d/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nuechter/slam6d/trunk/CMakeFiles /home/nuechter/slam6d/trunk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nuechter/slam6d/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hogman

# Build rule for target.
hogman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hogman
.PHONY : hogman

# fast build rule for target.
hogman/fast:
	$(MAKE) -f CMakeFiles/hogman.dir/build.make CMakeFiles/hogman.dir/build
.PHONY : hogman/fast

#=============================================================================
# Target rules for targets named slam

# Build rule for target.
slam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slam
.PHONY : slam

# fast build rule for target.
slam/fast:
	$(MAKE) -f CMakeFiles/slam.dir/build.make CMakeFiles/slam.dir/build
.PHONY : slam/fast

#=============================================================================
# Target rules for targets named toro3d

# Build rule for target.
toro3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 toro3d
.PHONY : toro3d

# fast build rule for target.
toro3d/fast:
	$(MAKE) -f CMakeFiles/toro3d.dir/build.make CMakeFiles/toro3d.dir/build
.PHONY : toro3d/fast

#=============================================================================
# Target rules for targets named ANN

# Build rule for target.
ANN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ANN
.PHONY : ANN

# fast build rule for target.
ANN/fast:
	$(MAKE) -f 3rdparty/CMakeFiles/ANN.dir/build.make 3rdparty/CMakeFiles/ANN.dir/build
.PHONY : ANN/fast

#=============================================================================
# Target rules for targets named ANN_s

# Build rule for target.
ANN_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ANN_s
.PHONY : ANN_s

# fast build rule for target.
ANN_s/fast:
	$(MAKE) -f 3rdparty/CMakeFiles/ANN_s.dir/build.make 3rdparty/CMakeFiles/ANN_s.dir/build
.PHONY : ANN_s/fast

#=============================================================================
# Target rules for targets named glui

# Build rule for target.
glui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glui
.PHONY : glui

# fast build rule for target.
glui/fast:
	$(MAKE) -f 3rdparty/CMakeFiles/glui.dir/build.make 3rdparty/CMakeFiles/glui.dir/build
.PHONY : glui/fast

#=============================================================================
# Target rules for targets named newmat

# Build rule for target.
newmat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 newmat
.PHONY : newmat

# fast build rule for target.
newmat/fast:
	$(MAKE) -f 3rdparty/CMakeFiles/newmat.dir/build.make 3rdparty/CMakeFiles/newmat.dir/build
.PHONY : newmat/fast

#=============================================================================
# Target rules for targets named newmat_s

# Build rule for target.
newmat_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 newmat_s
.PHONY : newmat_s

# fast build rule for target.
newmat_s/fast:
	$(MAKE) -f 3rdparty/CMakeFiles/newmat_s.dir/build.make 3rdparty/CMakeFiles/newmat_s.dir/build
.PHONY : newmat_s/fast

#=============================================================================
# Target rules for targets named sparse

# Build rule for target.
sparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sparse
.PHONY : sparse

# fast build rule for target.
sparse/fast:
	$(MAKE) -f 3rdparty/CMakeFiles/sparse.dir/build.make 3rdparty/CMakeFiles/sparse.dir/build
.PHONY : sparse/fast

#=============================================================================
# Target rules for targets named sparse_s

# Build rule for target.
sparse_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sparse_s
.PHONY : sparse_s

# fast build rule for target.
sparse_s/fast:
	$(MAKE) -f 3rdparty/CMakeFiles/sparse_s.dir/build.make 3rdparty/CMakeFiles/sparse_s.dir/build
.PHONY : sparse_s/fast

#=============================================================================
# Target rules for targets named convergence

# Build rule for target.
convergence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convergence
.PHONY : convergence

# fast build rule for target.
convergence/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/convergence.dir/build.make src/slam6d/CMakeFiles/convergence.dir/build
.PHONY : convergence/fast

#=============================================================================
# Target rules for targets named exportPoints

# Build rule for target.
exportPoints: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exportPoints
.PHONY : exportPoints

# fast build rule for target.
exportPoints/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/exportPoints.dir/build.make src/slam6d/CMakeFiles/exportPoints.dir/build
.PHONY : exportPoints/fast

#=============================================================================
# Target rules for targets named frame_to_graph

# Build rule for target.
frame_to_graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frame_to_graph
.PHONY : frame_to_graph

# fast build rule for target.
frame_to_graph/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/frame_to_graph.dir/build.make src/slam6d/CMakeFiles/frame_to_graph.dir/build
.PHONY : frame_to_graph/fast

#=============================================================================
# Target rules for targets named frames2riegl

# Build rule for target.
frames2riegl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frames2riegl
.PHONY : frames2riegl

# fast build rule for target.
frames2riegl/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/frames2riegl.dir/build.make src/slam6d/CMakeFiles/frames2riegl.dir/build
.PHONY : frames2riegl/fast

#=============================================================================
# Target rules for targets named graph_balancer

# Build rule for target.
graph_balancer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_balancer
.PHONY : graph_balancer

# fast build rule for target.
graph_balancer/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/graph_balancer.dir/build.make src/slam6d/CMakeFiles/graph_balancer.dir/build
.PHONY : graph_balancer/fast

#=============================================================================
# Target rules for targets named riegl2frames

# Build rule for target.
riegl2frames: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 riegl2frames
.PHONY : riegl2frames

# fast build rule for target.
riegl2frames/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/riegl2frames.dir/build.make src/slam6d/CMakeFiles/riegl2frames.dir/build
.PHONY : riegl2frames/fast

#=============================================================================
# Target rules for targets named scan_diff

# Build rule for target.
scan_diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_diff
.PHONY : scan_diff

# fast build rule for target.
scan_diff/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_diff.dir/build.make src/slam6d/CMakeFiles/scan_diff.dir/build
.PHONY : scan_diff/fast

#=============================================================================
# Target rules for targets named scan_io_ais

# Build rule for target.
scan_io_ais: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_ais
.PHONY : scan_io_ais

# fast build rule for target.
scan_io_ais/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_ais.dir/build.make src/slam6d/CMakeFiles/scan_io_ais.dir/build
.PHONY : scan_io_ais/fast

#=============================================================================
# Target rules for targets named scan_io_asc

# Build rule for target.
scan_io_asc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_asc
.PHONY : scan_io_asc

# fast build rule for target.
scan_io_asc/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_asc.dir/build.make src/slam6d/CMakeFiles/scan_io_asc.dir/build
.PHONY : scan_io_asc/fast

#=============================================================================
# Target rules for targets named scan_io_front

# Build rule for target.
scan_io_front: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_front
.PHONY : scan_io_front

# fast build rule for target.
scan_io_front/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_front.dir/build.make src/slam6d/CMakeFiles/scan_io_front.dir/build
.PHONY : scan_io_front/fast

#=============================================================================
# Target rules for targets named scan_io_iais

# Build rule for target.
scan_io_iais: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_iais
.PHONY : scan_io_iais

# fast build rule for target.
scan_io_iais/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_iais.dir/build.make src/slam6d/CMakeFiles/scan_io_iais.dir/build
.PHONY : scan_io_iais/fast

#=============================================================================
# Target rules for targets named scan_io_ifp

# Build rule for target.
scan_io_ifp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_ifp
.PHONY : scan_io_ifp

# fast build rule for target.
scan_io_ifp/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_ifp.dir/build.make src/slam6d/CMakeFiles/scan_io_ifp.dir/build
.PHONY : scan_io_ifp/fast

#=============================================================================
# Target rules for targets named scan_io_oct

# Build rule for target.
scan_io_oct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_oct
.PHONY : scan_io_oct

# fast build rule for target.
scan_io_oct/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_oct.dir/build.make src/slam6d/CMakeFiles/scan_io_oct.dir/build
.PHONY : scan_io_oct/fast

#=============================================================================
# Target rules for targets named scan_io_old

# Build rule for target.
scan_io_old: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_old
.PHONY : scan_io_old

# fast build rule for target.
scan_io_old/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_old.dir/build.make src/slam6d/CMakeFiles/scan_io_old.dir/build
.PHONY : scan_io_old/fast

#=============================================================================
# Target rules for targets named scan_io_ply

# Build rule for target.
scan_io_ply: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_ply
.PHONY : scan_io_ply

# fast build rule for target.
scan_io_ply/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_ply.dir/build.make src/slam6d/CMakeFiles/scan_io_ply.dir/build
.PHONY : scan_io_ply/fast

#=============================================================================
# Target rules for targets named scan_io_riegl_bin

# Build rule for target.
scan_io_riegl_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_riegl_bin
.PHONY : scan_io_riegl_bin

# fast build rule for target.
scan_io_riegl_bin/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_riegl_bin.dir/build.make src/slam6d/CMakeFiles/scan_io_riegl_bin.dir/build
.PHONY : scan_io_riegl_bin/fast

#=============================================================================
# Target rules for targets named scan_io_riegl_rgb

# Build rule for target.
scan_io_riegl_rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_riegl_rgb
.PHONY : scan_io_riegl_rgb

# fast build rule for target.
scan_io_riegl_rgb/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_riegl_rgb.dir/build.make src/slam6d/CMakeFiles/scan_io_riegl_rgb.dir/build
.PHONY : scan_io_riegl_rgb/fast

#=============================================================================
# Target rules for targets named scan_io_riegl_txt

# Build rule for target.
scan_io_riegl_txt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_riegl_txt
.PHONY : scan_io_riegl_txt

# fast build rule for target.
scan_io_riegl_txt/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_riegl_txt.dir/build.make src/slam6d/CMakeFiles/scan_io_riegl_txt.dir/build
.PHONY : scan_io_riegl_txt/fast

#=============================================================================
# Target rules for targets named scan_io_rts

# Build rule for target.
scan_io_rts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_rts
.PHONY : scan_io_rts

# fast build rule for target.
scan_io_rts/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_rts.dir/build.make src/slam6d/CMakeFiles/scan_io_rts.dir/build
.PHONY : scan_io_rts/fast

#=============================================================================
# Target rules for targets named scan_io_rts_map

# Build rule for target.
scan_io_rts_map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_rts_map
.PHONY : scan_io_rts_map

# fast build rule for target.
scan_io_rts_map/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_rts_map.dir/build.make src/slam6d/CMakeFiles/scan_io_rts_map.dir/build
.PHONY : scan_io_rts_map/fast

#=============================================================================
# Target rules for targets named scan_io_rxp

# Build rule for target.
scan_io_rxp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_rxp
.PHONY : scan_io_rxp

# fast build rule for target.
scan_io_rxp/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_rxp.dir/build.make src/slam6d/CMakeFiles/scan_io_rxp.dir/build
.PHONY : scan_io_rxp/fast

#=============================================================================
# Target rules for targets named scan_io_uos

# Build rule for target.
scan_io_uos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uos
.PHONY : scan_io_uos

# fast build rule for target.
scan_io_uos/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_uos.dir/build.make src/slam6d/CMakeFiles/scan_io_uos.dir/build
.PHONY : scan_io_uos/fast

#=============================================================================
# Target rules for targets named scan_io_uos_frames

# Build rule for target.
scan_io_uos_frames: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uos_frames
.PHONY : scan_io_uos_frames

# fast build rule for target.
scan_io_uos_frames/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_uos_frames.dir/build.make src/slam6d/CMakeFiles/scan_io_uos_frames.dir/build
.PHONY : scan_io_uos_frames/fast

#=============================================================================
# Target rules for targets named scan_io_uos_map

# Build rule for target.
scan_io_uos_map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uos_map
.PHONY : scan_io_uos_map

# fast build rule for target.
scan_io_uos_map/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_uos_map.dir/build.make src/slam6d/CMakeFiles/scan_io_uos_map.dir/build
.PHONY : scan_io_uos_map/fast

#=============================================================================
# Target rules for targets named scan_io_uos_map_frames

# Build rule for target.
scan_io_uos_map_frames: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uos_map_frames
.PHONY : scan_io_uos_map_frames

# fast build rule for target.
scan_io_uos_map_frames/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_uos_map_frames.dir/build.make src/slam6d/CMakeFiles/scan_io_uos_map_frames.dir/build
.PHONY : scan_io_uos_map_frames/fast

#=============================================================================
# Target rules for targets named scan_io_uos_rgb

# Build rule for target.
scan_io_uos_rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uos_rgb
.PHONY : scan_io_uos_rgb

# fast build rule for target.
scan_io_uos_rgb/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_uos_rgb.dir/build.make src/slam6d/CMakeFiles/scan_io_uos_rgb.dir/build
.PHONY : scan_io_uos_rgb/fast

#=============================================================================
# Target rules for targets named scan_io_wrl

# Build rule for target.
scan_io_wrl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_wrl
.PHONY : scan_io_wrl

# fast build rule for target.
scan_io_wrl/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_wrl.dir/build.make src/slam6d/CMakeFiles/scan_io_wrl.dir/build
.PHONY : scan_io_wrl/fast

#=============================================================================
# Target rules for targets named scan_io_x3d

# Build rule for target.
scan_io_x3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_x3d
.PHONY : scan_io_x3d

# fast build rule for target.
scan_io_x3d/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_x3d.dir/build.make src/slam6d/CMakeFiles/scan_io_x3d.dir/build
.PHONY : scan_io_x3d/fast

#=============================================================================
# Target rules for targets named scan_io_xyz

# Build rule for target.
scan_io_xyz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_xyz
.PHONY : scan_io_xyz

# fast build rule for target.
scan_io_xyz/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_xyz.dir/build.make src/slam6d/CMakeFiles/scan_io_xyz.dir/build
.PHONY : scan_io_xyz/fast

#=============================================================================
# Target rules for targets named scan_io_xyzr

# Build rule for target.
scan_io_xyzr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_xyzr
.PHONY : scan_io_xyzr

# fast build rule for target.
scan_io_xyzr/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_xyzr.dir/build.make src/slam6d/CMakeFiles/scan_io_xyzr.dir/build
.PHONY : scan_io_xyzr/fast

#=============================================================================
# Target rules for targets named scan_io_zahn

# Build rule for target.
scan_io_zahn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_zahn
.PHONY : scan_io_zahn

# fast build rule for target.
scan_io_zahn/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_zahn.dir/build.make src/slam6d/CMakeFiles/scan_io_zahn.dir/build
.PHONY : scan_io_zahn/fast

#=============================================================================
# Target rules for targets named scan_io_zuf

# Build rule for target.
scan_io_zuf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_zuf
.PHONY : scan_io_zuf

# fast build rule for target.
scan_io_zuf/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_io_zuf.dir/build.make src/slam6d/CMakeFiles/scan_io_zuf.dir/build
.PHONY : scan_io_zuf/fast

#=============================================================================
# Target rules for targets named scan_red

# Build rule for target.
scan_red: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_red
.PHONY : scan_red

# fast build rule for target.
scan_red/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_red.dir/build.make src/slam6d/CMakeFiles/scan_red.dir/build
.PHONY : scan_red/fast

#=============================================================================
# Target rules for targets named scanlib

# Build rule for target.
scanlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scanlib
.PHONY : scanlib

# fast build rule for target.
scanlib/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scanlib.dir/build.make src/slam6d/CMakeFiles/scanlib.dir/build
.PHONY : scanlib/fast

#=============================================================================
# Target rules for targets named scanlib_s

# Build rule for target.
scanlib_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scanlib_s
.PHONY : scanlib_s

# fast build rule for target.
scanlib_s/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scanlib_s.dir/build.make src/slam6d/CMakeFiles/scanlib_s.dir/build
.PHONY : scanlib_s/fast

#=============================================================================
# Target rules for targets named slam6D

# Build rule for target.
slam6D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slam6D
.PHONY : slam6D

# fast build rule for target.
slam6D/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/slam6D.dir/build.make src/slam6d/CMakeFiles/slam6D.dir/build
.PHONY : slam6D/fast

#=============================================================================
# Target rules for targets named show

# Build rule for target.
show: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 show
.PHONY : show

# fast build rule for target.
show/fast:
	$(MAKE) -f src/show/CMakeFiles/show.dir/build.make src/show/CMakeFiles/show.dir/build
.PHONY : show/fast

#=============================================================================
# Target rules for targets named 2DGridder

# Build rule for target.
2DGridder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 2DGridder
.PHONY : 2DGridder

# fast build rule for target.
2DGridder/fast:
	$(MAKE) -f src/grid/CMakeFiles/2DGridder.dir/build.make src/grid/CMakeFiles/2DGridder.dir/build
.PHONY : 2DGridder/fast

#=============================================================================
# Target rules for targets named calibrate

# Build rule for target.
calibrate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calibrate
.PHONY : calibrate

# fast build rule for target.
calibrate/fast:
	$(MAKE) -f src/pmd/CMakeFiles/calibrate.dir/build.make src/pmd/CMakeFiles/calibrate.dir/build
.PHONY : calibrate/fast

#=============================================================================
# Target rules for targets named convertToSLAM6D

# Build rule for target.
convertToSLAM6D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convertToSLAM6D
.PHONY : convertToSLAM6D

# fast build rule for target.
convertToSLAM6D/fast:
	$(MAKE) -f src/pmd/CMakeFiles/convertToSLAM6D.dir/build.make src/pmd/CMakeFiles/convertToSLAM6D.dir/build
.PHONY : convertToSLAM6D/fast

#=============================================================================
# Target rules for targets named extrinsic

# Build rule for target.
extrinsic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extrinsic
.PHONY : extrinsic

# fast build rule for target.
extrinsic/fast:
	$(MAKE) -f src/pmd/CMakeFiles/extrinsic.dir/build.make src/pmd/CMakeFiles/extrinsic.dir/build
.PHONY : extrinsic/fast

#=============================================================================
# Target rules for targets named grabFramesCam

# Build rule for target.
grabFramesCam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grabFramesCam
.PHONY : grabFramesCam

# fast build rule for target.
grabFramesCam/fast:
	$(MAKE) -f src/pmd/CMakeFiles/grabFramesCam.dir/build.make src/pmd/CMakeFiles/grabFramesCam.dir/build
.PHONY : grabFramesCam/fast

#=============================================================================
# Target rules for targets named grabFramesPMD

# Build rule for target.
grabFramesPMD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grabFramesPMD
.PHONY : grabFramesPMD

# fast build rule for target.
grabFramesPMD/fast:
	$(MAKE) -f src/pmd/CMakeFiles/grabFramesPMD.dir/build.make src/pmd/CMakeFiles/grabFramesPMD.dir/build
.PHONY : grabFramesPMD/fast

#=============================================================================
# Target rules for targets named grabVideoAnd3D

# Build rule for target.
grabVideoAnd3D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grabVideoAnd3D
.PHONY : grabVideoAnd3D

# fast build rule for target.
grabVideoAnd3D/fast:
	$(MAKE) -f src/pmd/CMakeFiles/grabVideoAnd3D.dir/build.make src/pmd/CMakeFiles/grabVideoAnd3D.dir/build
.PHONY : grabVideoAnd3D/fast

#=============================================================================
# Target rules for targets named pmdaccess2

# Build rule for target.
pmdaccess2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pmdaccess2
.PHONY : pmdaccess2

# fast build rule for target.
pmdaccess2/fast:
	$(MAKE) -f src/pmd/CMakeFiles/pmdaccess2.dir/build.make src/pmd/CMakeFiles/pmdaccess2.dir/build
.PHONY : pmdaccess2/fast

#=============================================================================
# Target rules for targets named pose

# Build rule for target.
pose: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pose
.PHONY : pose

# fast build rule for target.
pose/fast:
	$(MAKE) -f src/pmd/CMakeFiles/pose.dir/build.make src/pmd/CMakeFiles/pose.dir/build
.PHONY : pose/fast

#=============================================================================
# Target rules for targets named Pgm2asc

# Build rule for target.
Pgm2asc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Pgm2asc
.PHONY : Pgm2asc

# fast build rule for target.
Pgm2asc/fast:
	$(MAKE) -f src/shapes/CMakeFiles/Pgm2asc.dir/build.make src/shapes/CMakeFiles/Pgm2asc.dir/build
.PHONY : Pgm2asc/fast

#=============================================================================
# Target rules for targets named planes

# Build rule for target.
planes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 planes
.PHONY : planes

# fast build rule for target.
planes/fast:
	$(MAKE) -f src/shapes/CMakeFiles/planes.dir/build.make src/shapes/CMakeFiles/planes.dir/build
.PHONY : planes/fast

#=============================================================================
# Target rules for targets named autopano

# Build rule for target.
autopano: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autopano
.PHONY : autopano

# fast build rule for target.
autopano/fast:
	$(MAKE) -f src/slam6d/sift/CMakeFiles/autopano.dir/build.make src/slam6d/sift/CMakeFiles/autopano.dir/build
.PHONY : autopano/fast

#=============================================================================
# Target rules for targets named autopano-sift-c

# Build rule for target.
autopano-sift-c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autopano-sift-c
.PHONY : autopano-sift-c

# fast build rule for target.
autopano-sift-c/fast:
	$(MAKE) -f src/slam6d/sift/CMakeFiles/autopano-sift-c.dir/build.make src/slam6d/sift/CMakeFiles/autopano-sift-c.dir/build
.PHONY : autopano-sift-c/fast

#=============================================================================
# Target rules for targets named generatekeys

# Build rule for target.
generatekeys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generatekeys
.PHONY : generatekeys

# fast build rule for target.
generatekeys/fast:
	$(MAKE) -f src/slam6d/sift/CMakeFiles/generatekeys.dir/build.make src/slam6d/sift/CMakeFiles/generatekeys.dir/build
.PHONY : generatekeys/fast

#=============================================================================
# Target rules for targets named libsift

# Build rule for target.
libsift: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsift
.PHONY : libsift

# fast build rule for target.
libsift/fast:
	$(MAKE) -f src/slam6d/sift/CMakeFiles/libsift.dir/build.make src/slam6d/sift/CMakeFiles/libsift.dir/build
.PHONY : libsift/fast

src/slam6d/icp6D.o: src/slam6d/icp6D.cc.o
.PHONY : src/slam6d/icp6D.o

# target to build an object file
src/slam6d/icp6D.cc.o:
	$(MAKE) -f CMakeFiles/slam.dir/build.make CMakeFiles/slam.dir/src/slam6d/icp6D.cc.o
.PHONY : src/slam6d/icp6D.cc.o

src/slam6d/icp6D.i: src/slam6d/icp6D.cc.i
.PHONY : src/slam6d/icp6D.i

# target to preprocess a source file
src/slam6d/icp6D.cc.i:
	$(MAKE) -f CMakeFiles/slam.dir/build.make CMakeFiles/slam.dir/src/slam6d/icp6D.cc.i
.PHONY : src/slam6d/icp6D.cc.i

src/slam6d/icp6D.s: src/slam6d/icp6D.cc.s
.PHONY : src/slam6d/icp6D.s

# target to generate assembly for a file
src/slam6d/icp6D.cc.s:
	$(MAKE) -f CMakeFiles/slam.dir/build.make CMakeFiles/slam.dir/src/slam6d/icp6D.cc.s
.PHONY : src/slam6d/icp6D.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hogman"
	@echo "... rebuild_cache"
	@echo "... slam"
	@echo "... toro3d"
	@echo "... ANN"
	@echo "... ANN_s"
	@echo "... glui"
	@echo "... newmat"
	@echo "... newmat_s"
	@echo "... sparse"
	@echo "... sparse_s"
	@echo "... convergence"
	@echo "... exportPoints"
	@echo "... frame_to_graph"
	@echo "... frames2riegl"
	@echo "... graph_balancer"
	@echo "... riegl2frames"
	@echo "... scan_diff"
	@echo "... scan_io_ais"
	@echo "... scan_io_asc"
	@echo "... scan_io_front"
	@echo "... scan_io_iais"
	@echo "... scan_io_ifp"
	@echo "... scan_io_oct"
	@echo "... scan_io_old"
	@echo "... scan_io_ply"
	@echo "... scan_io_riegl_bin"
	@echo "... scan_io_riegl_rgb"
	@echo "... scan_io_riegl_txt"
	@echo "... scan_io_rts"
	@echo "... scan_io_rts_map"
	@echo "... scan_io_rxp"
	@echo "... scan_io_uos"
	@echo "... scan_io_uos_frames"
	@echo "... scan_io_uos_map"
	@echo "... scan_io_uos_map_frames"
	@echo "... scan_io_uos_rgb"
	@echo "... scan_io_wrl"
	@echo "... scan_io_x3d"
	@echo "... scan_io_xyz"
	@echo "... scan_io_xyzr"
	@echo "... scan_io_zahn"
	@echo "... scan_io_zuf"
	@echo "... scan_red"
	@echo "... scanlib"
	@echo "... scanlib_s"
	@echo "... slam6D"
	@echo "... show"
	@echo "... 2DGridder"
	@echo "... calibrate"
	@echo "... convertToSLAM6D"
	@echo "... extrinsic"
	@echo "... grabFramesCam"
	@echo "... grabFramesPMD"
	@echo "... grabVideoAnd3D"
	@echo "... pmdaccess2"
	@echo "... pose"
	@echo "... Pgm2asc"
	@echo "... planes"
	@echo "... autopano"
	@echo "... autopano-sift-c"
	@echo "... generatekeys"
	@echo "... libsift"
	@echo "... src/slam6d/icp6D.o"
	@echo "... src/slam6d/icp6D.i"
	@echo "... src/slam6d/icp6D.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

