# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ec2-user/3dtk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ec2-user/3dtk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ec2-user/3dtk/CMakeFiles /home/ec2-user/3dtk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ec2-user/3dtk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named headers

# Build rule for target.
headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 headers
.PHONY : headers

# fast build rule for target.
headers/fast:
	$(MAKE) -f CMakeFiles/headers.dir/build.make CMakeFiles/headers.dir/build
.PHONY : headers/fast

#=============================================================================
# Target rules for targets named average6DoFposes

# Build rule for target.
average6DoFposes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 average6DoFposes
.PHONY : average6DoFposes

# fast build rule for target.
average6DoFposes/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/average6DoFposes.dir/build.make src/slam6d/CMakeFiles/average6DoFposes.dir/build
.PHONY : average6DoFposes/fast

#=============================================================================
# Target rules for targets named b3dto3d

# Build rule for target.
b3dto3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 b3dto3d
.PHONY : b3dto3d

# fast build rule for target.
b3dto3d/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/b3dto3d.dir/build.make src/slam6d/CMakeFiles/b3dto3d.dir/build
.PHONY : b3dto3d/fast

#=============================================================================
# Target rules for targets named bps2txt

# Build rule for target.
bps2txt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bps2txt
.PHONY : bps2txt

# fast build rule for target.
bps2txt/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/bps2txt.dir/build.make src/slam6d/CMakeFiles/bps2txt.dir/build
.PHONY : bps2txt/fast

#=============================================================================
# Target rules for targets named convergence

# Build rule for target.
convergence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convergence
.PHONY : convergence

# fast build rule for target.
convergence/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/convergence.dir/build.make src/slam6d/CMakeFiles/convergence.dir/build
.PHONY : convergence/fast

#=============================================================================
# Target rules for targets named exportPoints

# Build rule for target.
exportPoints: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exportPoints
.PHONY : exportPoints

# fast build rule for target.
exportPoints/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/exportPoints.dir/build.make src/slam6d/CMakeFiles/exportPoints.dir/build
.PHONY : exportPoints/fast

#=============================================================================
# Target rules for targets named frame_to_graph

# Build rule for target.
frame_to_graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frame_to_graph
.PHONY : frame_to_graph

# fast build rule for target.
frame_to_graph/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/frame_to_graph.dir/build.make src/slam6d/CMakeFiles/frame_to_graph.dir/build
.PHONY : frame_to_graph/fast

#=============================================================================
# Target rules for targets named frames2pose

# Build rule for target.
frames2pose: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frames2pose
.PHONY : frames2pose

# fast build rule for target.
frames2pose/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/frames2pose.dir/build.make src/slam6d/CMakeFiles/frames2pose.dir/build
.PHONY : frames2pose/fast

#=============================================================================
# Target rules for targets named frames2riegl

# Build rule for target.
frames2riegl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frames2riegl
.PHONY : frames2riegl

# fast build rule for target.
frames2riegl/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/frames2riegl.dir/build.make src/slam6d/CMakeFiles/frames2riegl.dir/build
.PHONY : frames2riegl/fast

#=============================================================================
# Target rules for targets named framesdiff2frames

# Build rule for target.
framesdiff2frames: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 framesdiff2frames
.PHONY : framesdiff2frames

# fast build rule for target.
framesdiff2frames/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/framesdiff2frames.dir/build.make src/slam6d/CMakeFiles/framesdiff2frames.dir/build
.PHONY : framesdiff2frames/fast

#=============================================================================
# Target rules for targets named graph_balancer

# Build rule for target.
graph_balancer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_balancer
.PHONY : graph_balancer

# fast build rule for target.
graph_balancer/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/graph_balancer.dir/build.make src/slam6d/CMakeFiles/graph_balancer.dir/build
.PHONY : graph_balancer/fast

#=============================================================================
# Target rules for targets named pose2frames

# Build rule for target.
pose2frames: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pose2frames
.PHONY : pose2frames

# fast build rule for target.
pose2frames/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/pose2frames.dir/build.make src/slam6d/CMakeFiles/pose2frames.dir/build
.PHONY : pose2frames/fast

#=============================================================================
# Target rules for targets named riegl2frames

# Build rule for target.
riegl2frames: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 riegl2frames
.PHONY : riegl2frames

# fast build rule for target.
riegl2frames/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/riegl2frames.dir/build.make src/slam6d/CMakeFiles/riegl2frames.dir/build
.PHONY : riegl2frames/fast

#=============================================================================
# Target rules for targets named scan

# Build rule for target.
scan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan
.PHONY : scan

# fast build rule for target.
scan/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan.dir/build.make src/slam6d/CMakeFiles/scan.dir/build
.PHONY : scan/fast

#=============================================================================
# Target rules for targets named scan_diff

# Build rule for target.
scan_diff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_diff
.PHONY : scan_diff

# fast build rule for target.
scan_diff/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/scan_diff.dir/build.make src/slam6d/CMakeFiles/scan_diff.dir/build
.PHONY : scan_diff/fast

#=============================================================================
# Target rules for targets named slam6D

# Build rule for target.
slam6D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slam6D
.PHONY : slam6D

# fast build rule for target.
slam6D/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/slam6D.dir/build.make src/slam6d/CMakeFiles/slam6D.dir/build
.PHONY : slam6D/fast

#=============================================================================
# Target rules for targets named toGlobal

# Build rule for target.
toGlobal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 toGlobal
.PHONY : toGlobal

# fast build rule for target.
toGlobal/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/toGlobal.dir/build.make src/slam6d/CMakeFiles/toGlobal.dir/build
.PHONY : toGlobal/fast

#=============================================================================
# Target rules for targets named transformFrames

# Build rule for target.
transformFrames: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transformFrames
.PHONY : transformFrames

# fast build rule for target.
transformFrames/fast:
	$(MAKE) -f src/slam6d/CMakeFiles/transformFrames.dir/build.make src/slam6d/CMakeFiles/transformFrames.dir/build
.PHONY : transformFrames/fast

#=============================================================================
# Target rules for targets named pointfilter

# Build rule for target.
pointfilter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pointfilter
.PHONY : pointfilter

# fast build rule for target.
pointfilter/fast:
	$(MAKE) -f src/scanio/CMakeFiles/pointfilter.dir/build.make src/scanio/CMakeFiles/pointfilter.dir/build
.PHONY : pointfilter/fast

#=============================================================================
# Target rules for targets named scan_io_b3d

# Build rule for target.
scan_io_b3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_b3d
.PHONY : scan_io_b3d

# fast build rule for target.
scan_io_b3d/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_b3d.dir/build.make src/scanio/CMakeFiles/scan_io_b3d.dir/build
.PHONY : scan_io_b3d/fast

#=============================================================================
# Target rules for targets named scan_io_faro_xyz_rgbr

# Build rule for target.
scan_io_faro_xyz_rgbr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_faro_xyz_rgbr
.PHONY : scan_io_faro_xyz_rgbr

# fast build rule for target.
scan_io_faro_xyz_rgbr/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_faro_xyz_rgbr.dir/build.make src/scanio/CMakeFiles/scan_io_faro_xyz_rgbr.dir/build
.PHONY : scan_io_faro_xyz_rgbr/fast

#=============================================================================
# Target rules for targets named scan_io_helper

# Build rule for target.
scan_io_helper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_helper
.PHONY : scan_io_helper

# fast build rule for target.
scan_io_helper/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_helper.dir/build.make src/scanio/CMakeFiles/scan_io_helper.dir/build
.PHONY : scan_io_helper/fast

#=============================================================================
# Target rules for targets named scan_io_ks

# Build rule for target.
scan_io_ks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_ks
.PHONY : scan_io_ks

# fast build rule for target.
scan_io_ks/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_ks.dir/build.make src/scanio/CMakeFiles/scan_io_ks.dir/build
.PHONY : scan_io_ks/fast

#=============================================================================
# Target rules for targets named scan_io_ks_rgb

# Build rule for target.
scan_io_ks_rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_ks_rgb
.PHONY : scan_io_ks_rgb

# fast build rule for target.
scan_io_ks_rgb/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_ks_rgb.dir/build.make src/scanio/CMakeFiles/scan_io_ks_rgb.dir/build
.PHONY : scan_io_ks_rgb/fast

#=============================================================================
# Target rules for targets named scan_io_leica_xyzr

# Build rule for target.
scan_io_leica_xyzr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_leica_xyzr
.PHONY : scan_io_leica_xyzr

# fast build rule for target.
scan_io_leica_xyzr/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_leica_xyzr.dir/build.make src/scanio/CMakeFiles/scan_io_leica_xyzr.dir/build
.PHONY : scan_io_leica_xyzr/fast

#=============================================================================
# Target rules for targets named scan_io_ply

# Build rule for target.
scan_io_ply: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_ply
.PHONY : scan_io_ply

# fast build rule for target.
scan_io_ply/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_ply.dir/build.make src/scanio/CMakeFiles/scan_io_ply.dir/build
.PHONY : scan_io_ply/fast

#=============================================================================
# Target rules for targets named scan_io_riegl_rgb

# Build rule for target.
scan_io_riegl_rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_riegl_rgb
.PHONY : scan_io_riegl_rgb

# fast build rule for target.
scan_io_riegl_rgb/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_riegl_rgb.dir/build.make src/scanio/CMakeFiles/scan_io_riegl_rgb.dir/build
.PHONY : scan_io_riegl_rgb/fast

#=============================================================================
# Target rules for targets named scan_io_riegl_txt

# Build rule for target.
scan_io_riegl_txt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_riegl_txt
.PHONY : scan_io_riegl_txt

# fast build rule for target.
scan_io_riegl_txt/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_riegl_txt.dir/build.make src/scanio/CMakeFiles/scan_io_riegl_txt.dir/build
.PHONY : scan_io_riegl_txt/fast

#=============================================================================
# Target rules for targets named scan_io_rts

# Build rule for target.
scan_io_rts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_rts
.PHONY : scan_io_rts

# fast build rule for target.
scan_io_rts/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_rts.dir/build.make src/scanio/CMakeFiles/scan_io_rts.dir/build
.PHONY : scan_io_rts/fast

#=============================================================================
# Target rules for targets named scan_io_uos

# Build rule for target.
scan_io_uos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uos
.PHONY : scan_io_uos

# fast build rule for target.
scan_io_uos/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_uos.dir/build.make src/scanio/CMakeFiles/scan_io_uos.dir/build
.PHONY : scan_io_uos/fast

#=============================================================================
# Target rules for targets named scan_io_uos_rgb

# Build rule for target.
scan_io_uos_rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uos_rgb
.PHONY : scan_io_uos_rgb

# fast build rule for target.
scan_io_uos_rgb/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_uos_rgb.dir/build.make src/scanio/CMakeFiles/scan_io_uos_rgb.dir/build
.PHONY : scan_io_uos_rgb/fast

#=============================================================================
# Target rules for targets named scan_io_uos_rrgb

# Build rule for target.
scan_io_uos_rrgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uos_rrgb
.PHONY : scan_io_uos_rrgb

# fast build rule for target.
scan_io_uos_rrgb/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_uos_rrgb.dir/build.make src/scanio/CMakeFiles/scan_io_uos_rrgb.dir/build
.PHONY : scan_io_uos_rrgb/fast

#=============================================================================
# Target rules for targets named scan_io_uos_rrgbt

# Build rule for target.
scan_io_uos_rrgbt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uos_rrgbt
.PHONY : scan_io_uos_rrgbt

# fast build rule for target.
scan_io_uos_rrgbt/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_uos_rrgbt.dir/build.make src/scanio/CMakeFiles/scan_io_uos_rrgbt.dir/build
.PHONY : scan_io_uos_rrgbt/fast

#=============================================================================
# Target rules for targets named scan_io_uosr

# Build rule for target.
scan_io_uosr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_uosr
.PHONY : scan_io_uosr

# fast build rule for target.
scan_io_uosr/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_uosr.dir/build.make src/scanio/CMakeFiles/scan_io_uosr.dir/build
.PHONY : scan_io_uosr/fast

#=============================================================================
# Target rules for targets named scan_io_velodyne

# Build rule for target.
scan_io_velodyne: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_velodyne
.PHONY : scan_io_velodyne

# fast build rule for target.
scan_io_velodyne/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_velodyne.dir/build.make src/scanio/CMakeFiles/scan_io_velodyne.dir/build
.PHONY : scan_io_velodyne/fast

#=============================================================================
# Target rules for targets named scan_io_xyz

# Build rule for target.
scan_io_xyz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_xyz
.PHONY : scan_io_xyz

# fast build rule for target.
scan_io_xyz/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_xyz.dir/build.make src/scanio/CMakeFiles/scan_io_xyz.dir/build
.PHONY : scan_io_xyz/fast

#=============================================================================
# Target rules for targets named scan_io_xyz_rgb

# Build rule for target.
scan_io_xyz_rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_xyz_rgb
.PHONY : scan_io_xyz_rgb

# fast build rule for target.
scan_io_xyz_rgb/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_xyz_rgb.dir/build.make src/scanio/CMakeFiles/scan_io_xyz_rgb.dir/build
.PHONY : scan_io_xyz_rgb/fast

#=============================================================================
# Target rules for targets named scan_io_xyz_rgba

# Build rule for target.
scan_io_xyz_rgba: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_xyz_rgba
.PHONY : scan_io_xyz_rgba

# fast build rule for target.
scan_io_xyz_rgba/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_xyz_rgba.dir/build.make src/scanio/CMakeFiles/scan_io_xyz_rgba.dir/build
.PHONY : scan_io_xyz_rgba/fast

#=============================================================================
# Target rules for targets named scan_io_xyz_rrgb

# Build rule for target.
scan_io_xyz_rrgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_xyz_rrgb
.PHONY : scan_io_xyz_rrgb

# fast build rule for target.
scan_io_xyz_rrgb/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_xyz_rrgb.dir/build.make src/scanio/CMakeFiles/scan_io_xyz_rrgb.dir/build
.PHONY : scan_io_xyz_rrgb/fast

#=============================================================================
# Target rules for targets named scan_io_xyzr

# Build rule for target.
scan_io_xyzr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scan_io_xyzr
.PHONY : scan_io_xyzr

# fast build rule for target.
scan_io_xyzr/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scan_io_xyzr.dir/build.make src/scanio/CMakeFiles/scan_io_xyzr.dir/build
.PHONY : scan_io_xyzr/fast

#=============================================================================
# Target rules for targets named scanio

# Build rule for target.
scanio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scanio
.PHONY : scanio

# fast build rule for target.
scanio/fast:
	$(MAKE) -f src/scanio/CMakeFiles/scanio.dir/build.make src/scanio/CMakeFiles/scanio.dir/build
.PHONY : scanio/fast

#=============================================================================
# Target rules for targets named scanclient

# Build rule for target.
scanclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scanclient
.PHONY : scanclient

# fast build rule for target.
scanclient/fast:
	$(MAKE) -f src/scanserver/CMakeFiles/scanclient.dir/build.make src/scanserver/CMakeFiles/scanclient.dir/build
.PHONY : scanclient/fast

#=============================================================================
# Target rules for targets named scanserver

# Build rule for target.
scanserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scanserver
.PHONY : scanserver

# fast build rule for target.
scanserver/fast:
	$(MAKE) -f src/scanserver/CMakeFiles/scanserver.dir/build.make src/scanserver/CMakeFiles/scanserver.dir/build
.PHONY : scanserver/fast

#=============================================================================
# Target rules for targets named normals_panorama

# Build rule for target.
normals_panorama: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 normals_panorama
.PHONY : normals_panorama

# fast build rule for target.
normals_panorama/fast:
	$(MAKE) -f src/normals/CMakeFiles/normals_panorama.dir/build.make src/normals/CMakeFiles/normals_panorama.dir/build
.PHONY : normals_panorama/fast

#=============================================================================
# Target rules for targets named show

# Build rule for target.
show: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 show
.PHONY : show

# fast build rule for target.
show/fast:
	$(MAKE) -f src/show/CMakeFiles/show.dir/build.make src/show/CMakeFiles/show.dir/build
.PHONY : show/fast

#=============================================================================
# Target rules for targets named showstatic

# Build rule for target.
showstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 showstatic
.PHONY : showstatic

# fast build rule for target.
showstatic/fast:
	$(MAKE) -f src/show/CMakeFiles/showstatic.dir/build.make src/show/CMakeFiles/showstatic.dir/build
.PHONY : showstatic/fast

#=============================================================================
# Target rules for targets named b3dfile

# Build rule for target.
b3dfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 b3dfile
.PHONY : b3dfile

# fast build rule for target.
b3dfile/fast:
	$(MAKE) -f 3rdparty/CMakeFiles/b3dfile.dir/build.make 3rdparty/CMakeFiles/b3dfile.dir/build
.PHONY : b3dfile/fast

#=============================================================================
# Target rules for targets named glui

# Build rule for target.
glui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glui
.PHONY : glui

# fast build rule for target.
glui/fast:
	$(MAKE) -f 3rdparty/CMakeFiles/glui.dir/build.make 3rdparty/CMakeFiles/glui.dir/build
.PHONY : glui/fast

#=============================================================================
# Target rules for targets named apriltag

# Build rule for target.
apriltag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apriltag
.PHONY : apriltag

# fast build rule for target.
apriltag/fast:
	$(MAKE) -f 3rdparty/apriltag-2015-03-18/CMakeFiles/apriltag.dir/build.make 3rdparty/apriltag-2015-03-18/CMakeFiles/apriltag.dir/build
.PHONY : apriltag/fast

#=============================================================================
# Target rules for targets named correction

# Build rule for target.
correction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 correction
.PHONY : correction

# fast build rule for target.
correction/fast:
	$(MAKE) -f addons/CMakeFiles/correction.dir/build.make addons/CMakeFiles/correction.dir/build
.PHONY : correction/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... headers"
	@echo "... rebuild_cache"
	@echo "... average6DoFposes"
	@echo "... b3dto3d"
	@echo "... bps2txt"
	@echo "... convergence"
	@echo "... exportPoints"
	@echo "... frame_to_graph"
	@echo "... frames2pose"
	@echo "... frames2riegl"
	@echo "... framesdiff2frames"
	@echo "... graph_balancer"
	@echo "... pose2frames"
	@echo "... riegl2frames"
	@echo "... scan"
	@echo "... scan_diff"
	@echo "... slam6D"
	@echo "... toGlobal"
	@echo "... transformFrames"
	@echo "... pointfilter"
	@echo "... scan_io_b3d"
	@echo "... scan_io_faro_xyz_rgbr"
	@echo "... scan_io_helper"
	@echo "... scan_io_ks"
	@echo "... scan_io_ks_rgb"
	@echo "... scan_io_leica_xyzr"
	@echo "... scan_io_ply"
	@echo "... scan_io_riegl_rgb"
	@echo "... scan_io_riegl_txt"
	@echo "... scan_io_rts"
	@echo "... scan_io_uos"
	@echo "... scan_io_uos_rgb"
	@echo "... scan_io_uos_rrgb"
	@echo "... scan_io_uos_rrgbt"
	@echo "... scan_io_uosr"
	@echo "... scan_io_velodyne"
	@echo "... scan_io_xyz"
	@echo "... scan_io_xyz_rgb"
	@echo "... scan_io_xyz_rgba"
	@echo "... scan_io_xyz_rrgb"
	@echo "... scan_io_xyzr"
	@echo "... scanio"
	@echo "... scanclient"
	@echo "... scanserver"
	@echo "... normals_panorama"
	@echo "... show"
	@echo "... showstatic"
	@echo "... b3dfile"
	@echo "... glui"
	@echo "... apriltag"
	@echo "... correction"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

